name: final-dl-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - numpy
  - matplotlib
  - scipy
  - pandas
  - jupyter
  - ipywidgets
  - librosa
  - ffmpeg
  - pip
  - pip:
    - musdb
    - stempeg
    - tqdm
    - soundfile